name: tao_scrape
description: scrapes the tao of programming
version: 0.0.1
#author: randal stevens

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  html: any

dev_dependencies:
  test: ^0.12.0
